### ISSUE TITLE
album pages

### ISSUE THREAD

**Issue by henryott** [devintyler/2fcollective#4]
Album pages: I feel like there should be seperate album pages (i.e. 1 new webpage per album), so that the albums have their own space and aren’t crowding up the artist pages. Album pages should have: 
-picture of the album cover, 
-title (Artist name , then album name), 
-download button, 
-soundcloud playlist (to stream the album, this can appear to the right, same layout as artist pages) and ,
-liner notes (below)

for reference it might be worth it to take a look at how this band did their thing. it looks pretty classy and sober. http://site.darkstar.ws/     -> you gotta click on music  and then it takes you to an albums page and then clicking on any individual album brings you to that specific album page and it just has title, notes ("in their case they have press blurb, well just have our own liner notes"), album cover and soundcloud playlist.

**Comment by agoldgeier** [comment]
Done!

Still missing some liner notes though!
