### ISSUE TITLE
artist pages update:

### ISSUE THREAD

**Issue by henryott** [devintyler/2fcollective#5]

**Comment by henryott** [comment]
what should be on the artist pages now that we are making seperate album pages:
-artist profile picture
-title (name of artist)
-sound cloud playlist (most recent tracks) (quick note: i noticed i dont have one of these, could you put one on my page anyways. I beleieve I sent you the embed code for that before but if not let me know and ill send).
-bands in town (appearing as a widget, not link)
-albums (this can appear below all of this, each past album by an artist should appear on their page with a picture of the album cover, with album title below. Clicking on that picture or title should take you to the specific album page where you can stream that album. 
- a space to add other forms of media (youtube videos mainly)

**Comment by agoldgeier** [comment]
Also done!

Bandsintown is a separate issue, but everything is working together.

**Comment by agoldgeier** [comment]
Also, BXTR's secret playlist broke

**Comment by henryott** [comment]
Ya i noticed the BXTR playlist is broken. Ill email jake and get him to update it and resend the link. ill also ask him what to do about the BEat Mixtape, which is a sort of unofficial release.ill ask him if he wants an album page for it or maybe he just wants a link to the soundcloud playlist.  Error scheme and Out of Touch, the reason you can’t find the downloads is because they havent put that on band camp, they exist soley on soundcloud. Ill get on their asses about that so that the album pages can go up soon. 

thanks,

did you get anything cool at that electronics yard sale?

H
